# Generated by Django 4.1.6 on 2023-07-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0002_alter_mitra_luas_lahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='status_mitra',
            field=models.BooleanField(choices=[(True, 'Terdaftar'), (False, 'Belum Terdaftar')], default=False),
        ),
    ]
