# Generated by Django 4.1.6 on 2023-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0003_alter_mitra_status_mitra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitra',
            name='status_mitra',
            field=models.BooleanField(default=False),
        ),
    ]
